### ISSUE TITLE
Crash with Backslot mod when hitting keybind for switching slots

### ISSUE THREAD

**Issue by purrfait** [qouteall/ImmersivePortalsMod#1323]
[19:14:59] [Netty Server IO #5/ERROR]: Encountered exception while handling in channel with name "backslot:switch_item"
java.lang.IllegalArgumentException: Maybe a mod is trying to add entity in a non-server thread. This is probably not ImmPtl's issue

Crash with Backslot mod when hitting keybind for switching slots - Works fine when moving item to slots without the keybind

**Comment by qouteall** [comment]
Can you post the full crash report

**Comment by qouteall** [comment]
Investigation shows that the root cause is in BackSlot doing unsafe packet handling and ImmPtl's thread checking caused the crash. So it should be fixed on BackSlot side. However it cause some misunderstanding so I am going to make the check non-crashing.

**Comment by Snacj** [comment]
Im using the 2.3.2 version of Immersive Portals for 1.19.2. I still have the issue. Is there a way to deactivate the thread checking?
