### ISSUE TITLE
The player suffocates in blocks if portal is close to them.

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#370]
Example:
https://youtu.be/8kowW2km-gY

**Comment by qouteall** [comment]
Fixed in the latest version

**Comment by ImSpaceLover** [comment]
Can you reopen this issue please? It still happens. https://www.youtube.com/watch?v=5Ek-ga9YfMI

**Comment by ImSpaceLover** [comment]
Oops, that was wrong link. https://www.youtube.com/watch?v=irwrrhLLdS8

**Comment by qouteall** [comment]
Fixed. will be in the next version

**Comment by qouteall** [comment]
Fixed. will be in the next version
