### ISSUE TITLE
All of fabric 3 incompatible

### ISSUE THREAD

**Issue by GeneralZyonix** [qouteall/ImmersivePortalsMod#466]
The immersive portals mod wont load due to the Kibe mod inside this modpack... any way to get a fix for it to be compatible with the Kibe mod?

**Comment by qouteall** [comment]
Show the crash report

**Comment by GeneralZyonix** [comment]
`[02:27:21] [main/INFO]: ModLauncher running: args [--username, GeneralZyonix, --version, forge-33.0.36, --gameDir, C:\Users\Ashley\Documents\Curse\Minecraft\Instances\All of Fabric 3, --assetsDir, C:\Users\Ashley\Documents\Curse\Minecraft\Install\assets, --assetIndex, 1.16, --uuid, e80731ecdd6f4f5a8234c28f50c31b1a, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 33.0.36, --fml.mcVersion, 1.16.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200812.004259]
[02:27:21] [main/INFO]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_51 by Oracle Corporation
[02:27:21] [main/INFO]: OptiFineTransformationService.onLoad
[02:27:21] [main/INFO]: OptiFine ZIP file: C:\Users\Ashley\Documents\Curse\Minecraft\Instances\All of Fabric 3\mods\OptiFine_1.16.2_HD_U_G3.jar
[02:27:22] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[02:27:22] [main/INFO]: Jumploader 2.0.1 initialising, discovering environment...
[02:27:22] [main/INFO]: Detected environment link.infra.jumploader.resolution.EnvironmentDiscoverer.TwitchJarStorage [Minecraft version 1.16.2]
[02:27:22] [main/INFO]: Environment link.infra.jumploader.resolution.EnvironmentDiscoverer.TwitchJarStorage was incompatible with side null, switched to link.infra.jumploader.resolution.EnvironmentDiscoverer.TwitchJarStorage
[02:27:22] [main/INFO]: Configuration successfully loaded with sources: [minecraft, fabric] Resolving JARs to jumpload...
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/versions/1.16.2/1.16.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/patchy/1.1/patchy-1.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/google/guava/guava/21.0/guava-21.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./commons-io/commons-io/2.5/commons-io-2.5.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/authlib/1.6.25/authlib-1.6.25.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/fabric-loader/0.10.6+build.214/fabric-loader-0.10.6+build.214.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/intermediary/1.16.2/intermediary-1.16.2.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/ow2/asm/asm/9.0/asm-9.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
[02:27:22] [main/INFO]: Found JAR: file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
[02:27:22] [main/INFO]: Jumping to new loader, main class: net.fabricmc.loader.launch.knot.KnotClient
[02:27:24] [main/INFO]: [com.qouteall.hiding_in_the_bushes.LaunchMixinWithOptifineRunnable:run:10]: Registering Mixin for OptiFine
[02:27:24] [main/INFO]: [me.modmuss50.optifabric.mod.OptifineSetup:getRuntime:68]: Found existing patched optifine jar, using that
[02:27:24] [main/INFO]: [com.chocohead.mm.Plugin:getMixins:342]: Immersive Portals is still using the traditional Early Riser initialisation
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:180)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$51/1337335626.accept(Unknown Source)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
[02:27:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 8 more
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.reflect.InvocationTargetException
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 15 more
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:261)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_128.method_559(class_128.java:101)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_128.<init>(class_128.java:54)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_128.method_24305(class_128.java:413)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.main(Main.java:135)
[02:27:25] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 20 more
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; in kibe.mixins.json:ServerWorldMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kibe-1.16.3-refmap.json
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 31 more
e" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-9/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-6/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-30/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-5/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-18/WARN]: Non-Fabric mod JAR at "C:\Users\Ashley\Documents\Curse\Minecraft\Instances\All of Fabric 3\mods\OptiFine_1.16.2_HD_U_G3.jar", ignoring
[02:27:22] [ForkJoinPool-1-worker-12/WARN]: The mod "cardinal-components-world" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-5/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-31/WARN]: The mod "cardinal-components-chunk" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-30/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-6/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-23/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-6/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-30/WARN]: The mod "shulkerboxtooltip" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12
[02:27:22] [ForkJoinPool-1-worker-16/WARN]: The mod "qcommon-croco" contains invalid entries in its mod json:
- Unsupported root entry "links" at line 10 column 10
[02:27:22] [ForkJoinPool-1-worker-19/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-9/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-26/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-23/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-31/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-5/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-27/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-26/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[02:27:22] [ForkJoinPool-1-worker-11/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[02:27:22] [ForkJoinPool-1-worker-13/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [ForkJoinPool-1-worker-13/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[02:27:22] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474cfa, also found 0.1.3+12a8474c95, 0.1.3+12a8474c4e, 0.1.3+12a8474cb2, 0.1.3+12a8474ca7
 - Conflicting versions found for fabric-networking-v0: used 0.1.10+e00ecb5f4e, also found 0.1.10+e00ecb5fa7, 0.1.10+e00ecb5f95
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.1+730711c6a7, also found 1.0.1+730711c695
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.2.0+74cc3b2095, also found 1.2.0+74cc3b20a7
 - Conflicting versions found for fabric-events-lifecycle-v0: used 0.2.0+16acbe5b95, also found 0.2.0+16acbe5ba7
 - Mod 'Mouse Wheelie' (mousewheelie) conflicts with any version of mod 'Applied Energistics 2' (appliedenergistics2), but a matching version is present: 8.1.0-alpha.10!
	 - While this won't prevent you from starting the game, the developer(s) of 'Mouse Wheelie' (mousewheelie) have found that version 8.1.0-alpha.10 of 'Applied Energistics 2' (appliedenergistics2) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
	 - Mod 'Applied Energistics 2' (appliedenergistics2) v8.1.0-alpha.10 is being loaded from the user's mod directory.
 - Conflicting versions found for fabric-textures-v0: used 1.0.4+eae12eb84e, also found 1.0.4+eae12eb895
 - Mod 'Cardinal Components API (items)' (cardinal-components-item) conflicts with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.5.0!
	 - While this won't prevent you from starting the game, the developer(s) of 'Cardinal Components API (items)' (cardinal-components-item) have found that version 1.5.0 of 'OptiFabric' (optifabric) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
	 - Mod 'OptiFabric' (optifabric) v1.5.0 is being loaded from the user's mod directory.
 - Conflicting versions found for fabric-renderer-registries-v1: used 2.1.0+e2862de695, also found 2.1.0+e2862de64e
 - Mod 'Crooked Crooks' (crookedcrooks) recommends version 3.0.0 or later of mod 'LibCapableData' (libcd), but a non-matching version is present: 2.5.0+1.16.2!
	 - You must install version 3.0.0 or later of 'LibCapableData' (libcd).
	 - Mod 'LibCapableData' (libcd) v2.5.0+1.16.2 is being provided by 'Adorn' (adorn) v2.5.0+1.16.2.
[02:27:22] [main/WARN]: Mod `{}` ({}) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[02:27:22] [main/WARN]: Mod `{}` ({}) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[02:27:22] [main/INFO]: [FabricLoader] Loading 259 mods: fermion@2.1.191, fallflyinglib@1.1.0, couplings@1.3.1, crusade@1.1.4+1.16.2, roughlyenoughitems-api@5.5.1, kubejs@1.4.5, cloth-common-events-v1@1.4.8, ezpas@1.2.3-1.16.2, fabricloader@0.10.6+build.214, trinkets@2.6.4, cloth-durability-bar-api-v1@1.4.8, iron-jetpacks@0.2.5, kibe@1.4.3-BETA, megane@1.1.0+1.16, fabric-game-rule-api-v1@1.0.1+74685c1495, fermion-modkeys@1.8.180-snapshot, bettercaves@1.16.2-1.0.3, fabric-api-base@0.1.3+12a8474cfa, astromine-discoveries@1.10.7+fabric-1.16.3, cotton-cauldron@1.0.4, jumploader@2.0.1, org_joml_joml@1.9.25, maybe-data@1.0.0-1.16.2, packages@1.1, ce_foodstuffs@1.0.1, astromine@1.10.7+fabric-1.16.3, astromine-transportations@1.10.7+fabric-1.16.3, playerabilitylib@1.2.1, waila@1.9.22, astromine-foundations@1.10.7+fabric-1.16.3, villagerhats@fabric-1.16-rc1-1.0.0, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.0, woodenhoppers@1.0.0, fabric-diagonal-panes@0.3.1, fabric-networking-v0@0.1.10+e00ecb5f4e, dawn@1.2, pling@1.2.0, org_codehaus_groovy_groovy@3.0.3, techreborn@3.5.3+build.115, imm_ptl_core@0.32, cleancut@mc1.16-2.1-fabric, lapisreserve@1.0.6, tk_valoeghese_zoesteriaconfig@1.3.2, repurposed_structures@1.16.3-1.6.1, modmenu@1.14.6+build.31, flora-doubling@1.1.2, realistic_bakery_products@1.0.8, phosphor@0.6.0+build.7, cloth-utils-v1@1.4.8, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.0, roughlyenoughitems-runtime@5.5.1, rtree-3i-lite-fabric@0.3.0, structure-helpers@3.0.0, bebooks@1.1.2, voyager@1.0.0, fabric-crash-report-info-v1@0.1.2+b7f9825d95, mostructures@1.0.0-pre3+mc.1.16.2, fabric-key-binding-api-v1@1.0.1+730711c6a7, megane-runtime@1.1.0+1.16, chunkpregen@0.3.2, trapexpansion@1.3.2, universalcomponents@0.7.3+1.16.2, libblockattributes_fluids@0.8.2-pre.6, staticdata@1.1.2, magna@1.4.2-1.16.2, adorn@1.11.0+1.16.2, cotton-player-events@1.0.2, rgbable@1.0.0, org_jetbrains_annotations@20.0.0, parchment@1.0.2+1.15.2, dwarfcoal@1.16.2-1.0.0, notes@1.0.3, mambience@2.1.0+1.16.2, vanillaexcavators@1.1.0, fabric-structure-api-v1@1.0.1+fb0d9b0e95, libaddict@0.2.1, lithium@0.5.4, fabric-object-builder-api-v1@1.8.0+c1aa8ed895, hctm-base@3.4.0, ringsofascension@1.0.7, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d95, hardcorequesting@0.3.1, wolveswitharmor@1.5.2-1.16.2, linkart@unspecified, reach-entity-attributes@1.0.1, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, cardinal-components-util@2.6.0, immersive_portals@0.32, fabric-loot-tables-v1@1.0.1+432ea18895, dynamicfps@1.2.1, cloth-armor-api-v1@1.4.8, goml@1.2.1-beta, libblockattributes_core@0.8.2-pre.6, decimal_coins@1.16.2-1.2.0, bambootweaks@unspecified, minecraft@1.16.2, compressedblocks@1.0, boringbackgrounds@3.0.2+1.16.3, ktdatataglib@1.4.0, jankson@3.0.1+j1.2.0, fabric-command-api-v1@1.0.8+5ce5339895, cotton-commons@1.0.4, fabric-renderer-indigo@0.4.0+8bcfced895, advancements-enlarger@0.2.3, shapes@2.0.0+build.10, libgui@3.0.0-beta.1+1.16.2-rc2, cardinal-components@2.6.0, slight-gui-modifications@1.4.0, xaerominimap@20.23.0, fabric-rendering-v0@1.1.0+5341049095, fabric-rendering-v1@1.3.0+432ea18895, givemehats@1.2.8, autoconfig1u@3.2.2, winged@1.16.2-1.4.0, harvest@1.2.12, library_of_exile@1.0.4, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, blue_endless_jankson@+, inmis@1.3.0-1.16.2, can-i-mine-this-block@1.0.2, appleskin@1.0.11, cloth-api@1.4.8, smootherbedrock@1.0.0, byg@1.0.12, cloth-datagen-api-v1@1.4.8, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, horseinfo@0.2.2-1.16.1, team_reborn_energy@0.1.0, tweed@3.0.0-beta.13, fabric-keybindings-v0@0.2.0+3fa9f7c595, no-potion-offset@1.0.1-unstable, dungeons_of_exile@1.0.0, artifice@0.13.1+1.16.2-rc1, stonecutter-tweaks@1.1.0-1.16, indrev@1.6.11-BETA, healthoverlay@3.6.12, staffofbuilding@1.2.3-1.16.2, glassential@1.16.1-1.1.4, reborncore@4.4.1+build.69, controlling@1.1.2, xaeroworldmap@1.11.0, dankstorage@1.7-1.16.2, jumpoverfences@1.16-0.0.3, diggusmaximus@1.4.0-1.16.2, fiber@0.23.0-2, roughlyenoughresources@2.1.2, cardinal-components-level@2.6.0, org_jetbrains_kotlin_kotlin-stdlib@1.4.0, com_moandjiezana_toml_toml4j@0.7.2, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, libblockattributes_items@0.8.2-pre.6, fabric@0.21.0+build.407-1.16, cardinal-components-scoreboard@2.6.0, gameinfo@2.0.0a-experimental-06.1 1.16.2, respawnablepets@6, dml-refabricated@0.3.1-beta4, cotton-config@1.0.0-rc.7, wrenchable@1.0.0+1.16.1, tis3d@1.5.0, fabric-screen-handler-api-v1@1.1.0+8724984195, improved-stations@2.0.3, com_github_therandomlabs_trlutils-config@master-SNAPSHOT, eggtab@1.3.0+1.16-fabric, wild_explorer@1.1, tacocraft@1.3.1+mc.1.16, fabric-tool-attribute-api-v1@1.2.2+ccce563e95, angerable-patch@1.0.0-1.16.1, cloth-client-events-v0@1.4.8, blockus@1.6.3.2, fabric-events-interaction-v0@0.4.0+e2e6cdad95, disablecustomworldsadvice@1.0, com_github_nathanpb_safer@1.1.0, fabric-language-kotlin@1.4.0+build.1, patchouli@1.16.2-44-FABRIC, mousewheelie@1.5.5+mc1.16.2-pre1, cloth-config2@4.8.2, hard-hat-steve@1.1.1, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.9, fabric-resource-loader-v0@0.3.1+facf3bbf95, endreborn@1.8, chainmail@0.5.0, org_jetbrains_kotlin_kotlin-reflect@1.4.0, expandedstorage@5.6.29, cardinal-components-entity@2.6.0, computercraft@1.91.2, astromine-technologies@1.10.7+fabric-1.16.3, cherishedworlds@1.1.0-1.16.2, fabric-registry-sync-v0@0.5.0+c1aa8ed895, fabric-commands-v0@0.2.0+52d3083695, cardinal-components-base@2.6.0, lightoverlay@5.5.3, rswires@4.9.1, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-models-v0@0.1.0+dfdb52d695, fabric-item-groups-v0@0.2.0+438f963695, shulkerboxtooltip@2.1.1+1.16.2, craftpresence@1.7.1, fabric-renderer-api-v1@0.3.0+8bcfced895, inventorysorter@1.7.2-1.16, megane-api@1.1.0+1.16, libcd@2.5.0+1.16.2, cardinal-components-block@2.6.0, mycommands@1.16.1-17, cotton@1.0.7, vanilla-hammers@2.0.8-1.16.2, allure@1.2.6, simpleteleporters@2.2.1, blade@2.0.0, flonters@1.1.1+1.16.2, fabric-containers-v0@0.1.8+045df74f95, appliedenergistics2@8.1.0-alpha.10, mm@2.1, cloth-dynamic-registry-api-v1@1.4.8, campanion@1.2.0+build.39, fabric-textures-v0@1.0.4+eae12eb84e, cardinal-components-item@2.6.0, sandwichable@1.1.2, com_electronwill_night-config_core@3.6.0, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e95, qcommon-cfg-core@3.2.0, bedspreads@1.1.0-1.16.2, cloth-scissors-api-v1@1.4.8, cotton-logging@1.0.0-rc.4, glassdoor@1.5.0-1.16, cardinal-components-chunk@2.6.0, fabric-renderer-registries-v1@2.1.0+e2862de695, com_github_therandomlabs_trlutils-fabric@1.16-SNAPSHOT, quickshulker@1.1.6-1.16, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, okzoomer@4.0.1+1.16.2, roughlyenoughitems-default-plugin@5.5.1, crookedcrooks@1.3.0+1.16.3, cloth-basic-math@0.5.1, javax_vecmath_vecmath@1.5.2, qcommon-croco@2.1.1, fatxporbs@0.0.7, static-content@1.0.1-1.16.2, amecsapi@1.1.1+mc1.16-rc1, com_electronwill_night-config_toml@3.6.0, cotton-datapack@1.0.7, fabric-item-api-v1@1.1.0+29679fd695, roughlyenoughitems@5.5.1, kyrptconfig@1.1.2-1.16, megane-impl@1.1.0+1.16, iknowwhatimdoing@3.0.0, fabric-content-registries-v0@0.1.9+059ea86695, cardinal-components-world@2.6.0, fabric-biome-api-v1@2.0.0+c29459ab95, fabric-furnaces@1.3.2-1.16.2, optifabric@1.5.0, vanilladeathchest@1.16.3-1.11.0.7-fabric, mcdict@1.0.0+1.16.2, yosbr@0.1.1, libstructure@1.5, astromine-core@1.10.7+fabric-1.16.3, org_codehaus_groovy_groovy-jsr223@3.0.3, fabric-object-builders-v0@0.7.0+432ea18895, secretrooms@0.9.2+1.16.2
[02:27:22] [main/WARN]: Mod `villagerhats` (fabric-1.16-rc1-1.0.0) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `cleancut` (mc1.16-2.1-fabric) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `linkart` (unspecified) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `bambootweaks` (unspecified) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `gameinfo` (2.0.0a-experimental-06.1 1.16.2) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `com_github_therandomlabs_trlutils-config` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[02:27:22] [main/WARN]: Mod `blockus` (1.6.3.2) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[02:27:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Ashley/Documents/Curse/Minecraft/Instances/All%20of%20Fabric%203/../../Install/libraries/./net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[02:27:23] [main/WARN]: Reference map 'give-me-hats-1.16-refmap.json' for givemehats.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/INFO]: Loaded configuration file for Lithium: 63 options available, 1 override(s) found
[02:27:23] [main/WARN]: Reference map 'mixins/iknowwhatimdoing/refmap.json' for mixins/iknowwhatimdoing/mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'static-content-refmap.json' for static-content.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'astromine-transportations-refmap.json' for astromine-transportations.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'ezpas-refmap.json' for ezpas.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'fabric-diagonal-panes-refmap.json' for fabric-diagonal-panes.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'blade-2.0.0+fabric-1.16.3-refmap.json' for blade.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'wrenchable-refmap.json' for wrenchable.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'astromine-technologies-refmap.json' for astromine-technologies.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: Reference map 'astromine-foundations-refmap.json' for astromine-foundations.mixins.json could not be read. If this is a development environment you can ignore this message
[02:27:23] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[02:27:23] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.MixinThreadedAnvilChunkStorage' as rule 'mixin.world.player_chunk_tick' (added by user configuration) disables it and children
[02:27:23] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[02:27:23] [main/WARN]: Error loading class: net/minecraft/client/MinecraftClient (java.lang.ClassNotFoundException: net/minecraft/client/MinecraftClient)
[02:27:23] [main/WARN]: @Mixin target net.minecraft.client.MinecraftClient was not found mixins/iknowwhatimdoing/mixins.json:IKnowWhatImDoing
[02:27:24] [main/WARN]: @Mixin target net.optifine.DynamicLights is public in imm_ptl_optifine.mixins.json:MixinDynamicLights and should be specified in value
[02:27:25] [main/WARN]: @Redirect conflict. Skipping kibe.mixins.json:ServerWorldMixin->@Redirect::redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000, already redirected by imm_ptl.mixins.json:common.MixinServerWorld->@Redirect::redirectGetForcedChunks(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000
`

**Comment by GeneralZyonix** [comment]
https://pastebin.pl/view/e5ff35c4

**Comment by GeneralZyonix** [comment]
[02:27:25] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; in kibe.mixins.json:ServerWorldMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kibe-1.16.3-refmap.json

**Comment by GeneralZyonix** [comment]
When removing Kibe mod it works

**Comment by GeneralZyonix** [comment]
but it's part of the all of fabric modpack so i would like to keep it

**Comment by qouteall** [comment]
You are using 1.16.2? It has been fixed in the 1.16.3 version of this mod

**Comment by GeneralZyonix** [comment]
I have tried using immersive-portals-0.41-mc1.16.3-fabric.jar and still an error.. one sec ill post the logs

**Comment by GeneralZyonix** [comment]
look at the bottom.. it says it needs MC 1.16.3 but the pack is 1.16.2..

https://pastebin.pl/view/81bf9820

**Comment by GeneralZyonix** [comment]
Which is weird because the pack uses many mods for 1.16.3 and they seem to work fine

**Comment by qouteall** [comment]
Close because outdated.
