### ISSUE TITLE
Alternate dimensions' sky are black when using with Iris

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#850]
with bsl shader

**Comment by IMS212** [comment]
This isn't alternate dimension specific. Reloading shaders while inside the Nether causes the Overworld to break as well.

**Comment by qouteall** [comment]
@IMS212 that issue is fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.29-1.17

**Comment by lilynet336** [comment]
I'm having this issue with no shaders, I have updated and it still happens.

**Comment by qouteall** [comment]
@bobbyl140 open a new issue and provide screenshot
