### ISSUE TITLE
GUI rendering abnormal on Intel videocard

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#916]
Although it may not be IP's fault, there may be workarounds.

**Comment by muzikbike** [comment]
A comment somewhere implied that this may be due to a portal plane being rendered on top of UI elements. I've managed to enter a situation that strongly implies this, as hotbar items can be partially occluded:
![2022-02-22_19 57 16](https://user-images.githubusercontent.com/52297970/155209310-fe4f5a9b-50c6-49b8-8f2c-39f32c18dc19.png)
![2022-02-22_19 57 18](https://user-images.githubusercontent.com/52297970/155209317-64d22bf4-2cf6-4577-88a9-5c916041dfcf.png)
![2022-02-22_19 57 20](https://user-images.githubusercontent.com/52297970/155209320-cc9a3f96-c378-4db6-99fb-7525d63ec6f0.png)
![2022-02-22_19 57 27](https://user-images.githubusercontent.com/52297970/155209323-a9c2b392-2e1d-47f9-87df-c688ba037ef0.png)

**Comment by Redd56** [comment]
So depth buffer issue maybe? Somehow gui getting confused for the portal?

**Comment by CtrlAltWaverick** [comment]
dropping any "hidden" item causes all hidden items to reappear, temporary workaround?

**Comment by qouteall** [comment]
Maybe fixed in https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.3.4-1.18 (I am not sure)

**Comment by qouteall** [comment]
probably fixed

**Comment by antonguay3** [comment]
Not fixed on 1.18.1
![2023-06-17_01 28 26](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/136863111/5d3ff39d-c8e4-4406-98b6-c16b1e52118e)
![2023-06-17_01 28 08](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/136863111/93f2fe89-d75c-496d-9d19-bfef66a376e5)
